name:                AoC2017
version:             0.1.0.0
github:              IQubic/AoC2017
license:             BSD3
author:              Avi Caspe
maintainer:          avi.caspe@gmail.com
copyright:           BSD 3

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/IQubic/AoC2017#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  AoC2017-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AoC2017

tests:
  AoC2017-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AoC2017
